### ISSUE TITLE
Where is serving directory?

### ISSUE THREAD

**Issue by elcolie** [zolweb/docker-php7#10]
Sorry for this easy question.  I am running your `image` originally from dockerhub, but I don't get any `response` back from `server`. I use `GET http://localhost:80`

```
version: '3.3'
services:
  web:
#    build:
#      context: '5.0'
#      dockerfile: Dockerfile
    image: zolweb/php7:1.0
    container_name: php74
#    volumes:
#      - .:/var/www/html/
#    ports:
#      - 8000:80
  db:
    container_name: mysql5
    image: mysql:5
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - 6033:3306
```

**Comment by ChristopheZOL** [comment]
There is no serving directory because this image is only used for php-fpm. If you want a web server, you may use you own docker image like zolweb/docker-nginx-sf.

See default.conf for an example on [how to use it with php on port 9000](https://github.com/zolweb/docker-nginx-sf/blob/master/3.0-alpine/nginx/default.conf)
